### ISSUE TITLE
Note after re-run doesn't exist.

### ISSUE THREAD

**Issue by Slasheruus** [Cognifide/aet#443] opened 2018-11-27 13:41 UTC
There are 4 levels of notes. 
1(suite level) - it works properly. 
2(test level)  - it works properly. 
3(url level)  - it works properly. 
4(case level)  - after re-run the note disappears.
* Version used: 3.1.0

**To Reproduce**
1.Add note on each level.
2. Save the changes
3.Re-run the same suite and open the newest report.
4. There are no note on the level  4

**Expected behavior**
There are note on the level 4

**Comment by Skejven** [comment] 2018-11-27 13:53
There is one more level - `case level` which was not working properly and fixed in #363 .

**Comment by wblachowski** [comment] 2019-02-01 13:09
Can't reproduce this bug with AET 3.2.0 and changes from PR #363.

**Comment by RdkLwg** [comment] 2019-06-14 15:53
The issue still exists in the version 3.2.2.

**Comment by Cich0sza** [comment] 2019-08-01 13:06
Can't reproduce this bug in the current version of AET. Maybe it's related with specific suite configuration.

**Comment by RdkLwg** [comment] 2020-01-22 13:08
Looks like the issue no longer exists.

**Closed by RdkLwg** 2020-01-22 13:08 UTC
Labels: bug, help wanted, sum19

**Comment by annabudziszewska** [comment] 2020-10-22 13:33
Tested and accepted
Separate issue concerning notes has been reported: https://github.com/Cognifide/aet/issues/584
